<a href="https://colab.research.google.com/github/sekhahelina/ML_tasks/blob/main/Module3/HW_%D0%90%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC%D0%B8_%D0%BA%D0%BB%D0%B0%D1%81%D1%82%D0%B5%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D1%96%D1%97.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Домашнє завдання: Кластеризація в Аналізі Персоналій Клієнтів

#### Контекст
В цьому ДЗ ми скористаємось алгоритмами кластеризації для задачі аналізу портретів клієнтів (Customer Personality Analysis).

Customer Personality Analysis - це аналіз різних сегментів клієнтів компанії. Цей аналіз дозволяє бізнесу краще розуміти своїх клієнтів і полегшує процес адаптації продуктів під конкретні потреби, поведінку та інтереси різних типів клієнтів.

Аналіз портретів клієнтів допомагає бізнесу змінювати свій продукт на основі цільової аудиторії, розділеної на різні сегменти. Наприклад, замість того, щоб витрачати гроші на маркетинг нового продукту для всіх клієнтів у базі даних компанії, бізнес може проаналізувати, який сегмент клієнтів найімовірніше придбає продукт, і потім зосередити маркетингові зусилля лише на цьому сегменті.

#### Завдання
На основі наданих даних в файлі `marketing_campaign.csv` потрібно виконати кластеризацію, щоб виявити сегменти клієнтів.

#### Вхідні дані
Вам надано набір даних з такими атрибутами:

**Характеристики користувачів:**
- `ID`: Унікальний ідентифікатор клієнта
- `Year_Birth`: Рік народження клієнта
- `Education`: Рівень освіти клієнта
- `Marital_Status`: Сімейний стан клієнта
- `Income`: Річний дохід домогосподарства клієнта
- `Kidhome`: Кількість дітей у домогосподарстві клієнта
- `Teenhome`: Кількість підлітків у домогосподарстві клієнта
- `Dt_Customer`: Дата реєстрації клієнта у компанії
- `Recency`: Кількість днів з моменту останньої покупки клієнта
- `Complain`: 1, якщо клієнт скаржився за останні 2 роки, 0 - якщо ні

**Продукти:**
- `MntWines`: Сума, витрачена на вино за останні 2 роки
- `MntFruits`: Сума, витрачена на фрукти за останні 2 роки
- `MntMeatProducts`: Сума, витрачена на м'ясні продукти за останні 2 роки
- `MntFishProducts`: Сума, витрачена на рибні продукти за останні 2 роки
- `MntSweetProducts`: Сума, витрачена на солодощі за останні 2 роки
- `MntGoldProds`: Сума, витрачена на золото за останні 2 роки

**Акції:**
- `NumDealsPurchases`: Кількість покупок, зроблених з використанням знижок
- `AcceptedCmp1`: 1, якщо клієнт прийняв пропозицію у першій кампанії, 0 - якщо ні
- `AcceptedCmp2`: 1, якщо клієнт прийняв пропозицію у другій кампанії, 0 - якщо ні
- `AcceptedCmp3`: 1, якщо клієнт прийняв пропозицію у третій кампанії, 0 - якщо ні
- `AcceptedCmp4`: 1, якщо клієнт прийняв пропозицію у четвертій кампанії, 0 - якщо ні
- `AcceptedCmp5`: 1, якщо клієнт прийняв пропозицію у п'ятій кампанії, 0 - якщо ні
- `Response`: 1, якщо клієнт прийняв пропозицію в останній кампанії, 0 - якщо ні

**Взаємодія з компанією:**
- `NumWebPurchases`: Кількість покупок, зроблених через вебсайт компанії
- `NumCatalogPurchases`: Кількість покупок, зроблених за каталогом
- `NumStorePurchases`: Кількість покупок, зроблених безпосередньо у магазинах
- `NumWebVisitsMonth`: Кількість відвідувань вебсайту компанії за останній місяць

In [67]:
import pandas as pd
from sklearn.preprocessing import  OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import plotly.express as px

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

**Завдання 1**. Завантажте дані з `marketing_campaign.csv` в Pandas dataframe і виведіть основну інформацію про дані: скільки всього рядків і колонок, які типи даних мають колонки, скільки пропущених значень.

In [46]:
data = pd.read_csv("/content/drive/MyDrive/dataframes/marketing_campaign.csv", sep='\t')
data.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

In [47]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: float64(1), int64(25), object(3)
memory usage: 507.6+ KB

Дані містять 2240 рядків та 29 колонок. Серед них 2 категорії з типом object - це категоріальні значення. Також присутня одна колонка - float, яка містить в собі значення доходів. Усі інші категорії мають тип int64.

Одразу видалимо колонку з ID так як вона не несе ніякої потрібної інформації.

In [48]:
data.drop(columns='ID', inplace=True)

In [49]:
data.describe()

,Year_Birth,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
count,2240.000000,2216.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,...,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.0,2240.0,2240.000000
mean,1968.805804,52247.251354,0.444196,0.506250,49.109375,303.935714,26.302232,166.950000,37.525446,27.062946,...,5.316518,0.072768,0.074554,0.072768,0.064286,0.013393,0.009375,3.0,11.0,0.149107
std,11.984069,25173.076661,0.538398,0.544538,28.962453,336.597393,39.773434,225.715373,54.628979,41.280498,...,2.426645,0.259813,0.262728,0.259813,0.245316,0.114976,0.096391,0.0,0.0,0.356274
min,1893.000000,1730.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
25%,1959.000000,35303.000000,0.000000,0.000000,24.000000,23.750000,1.000000,16.000000,3.000000,1.000000,...,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
50%,1970.000000,51381.500000,0.000000,0.000000,49.000000,173.500000,8.000000,67.000000,12.000000,8.000000,...,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
75%,1977.000000,68522.000000,1.000000,1.000000,74.000000,504.250000,33.000000,232.000000,50.000000,33.000000,...,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
max,1996.000000,666666.000000,2.000000,2.000000,99.000000,1493.000000,199.000000,1725.000000,259.000000,263.000000,...,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.0,11.0,1.000000

In [50]:
data.isna().sum()

Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

Бачимо, що пропущені значення є лише у категорії income. Проте, їх небагато, приблизно 1 відсоток.

**Завдання 2.** Заповніть пропущені значення з врахуванням того завдання (кластеризація), яке ми виконуємо. Поясніть свій вибір заповнення пропущених значень.

Оскільки пропущені значення становлять лише близько 1% від усіх даних, їх видалення не призведе до суттєвої втрати інформації та не змінить загальний розподіл. Тому я обираю видалення цих рядків, щоб уникнути внесення штучних значень, які можуть викривити розрахунок відстаней під час кластеризації

In [51]:
data.dropna(subset=['Income'], inplace=True)

In [52]:
data['Income'].isna().sum()

np.int64(0)

**Завдання 3.** У нас є декілька колонок з категоріальними значеннями та одна колонка з датою. Як би ви обробили ці колонки для того, аби передати їх в алгоритм кластеризації?

Реалізуйте обробку категоріальних колонок і колонки з датою та перетворіть їх на ознаки, корисні для кластеризації з вашого погляду.

In [53]:
data['Education'].value_counts()

Education
Graduation    1116
PhD            481
Master         365
2n Cycle       200
Basic           54
Name: count, dtype: int64

Об`єднаємо категорії 2n cycle та Master, тому що вони здебільшого означають те саме.

In [54]:
data['Education'] = data['Education'].replace({
    '2n Cycle': 'Master'
})

In [55]:
data['Education'].value_counts()

Education
Graduation    1116
Master         565
PhD            481
Basic           54
Name: count, dtype: int64

Кодуємо за допомогою Ordinal encoding

In [56]:
encoder = OrdinalEncoder(categories=[['Basic', 'Graduation', 'Master', 'PhD']])
data['Education'] = encoder.fit_transform(data[['Education']])

Переходимо до Marital_status - колонка, що показує сімейний стан

In [57]:
data['Marital_Status'].value_counts()

Marital_Status
Married     857
Together    573
Single      471
Divorced    232
Widow        76
Alone         3
Absurd        2
YOLO          2
Name: count, dtype: int64

Вважаю, що варто спростити категорію Marital_Status. Рідкісні та недоречні значення (Absurd, YOLO, Alone) фактично позначають одиноких людей і їх можна об'єднати з Single. Щоб не створювати зайвих колонок після One-Hot Encoding, створимо єдину бінарну ознаку In_Relationship, де 1 відповідає перебуванню у стосунках (Married, Together), а 0 — самотній людині (Single, Divorced, Widow, Alone, Absurd, YOLO).

In [58]:
data['Marital_Status'] = data['Marital_Status'].replace({
    'Alone': 'Single',
    'Absurd': 'Single',
    'YOLO': 'Single'
})

data['In_Relationship'] = data['Marital_Status'].isin(['Married', 'Together']).astype(int)

In [59]:
data['In_Relationship'].value_counts()

In_Relationship
1    1430
0     786
Name: count, dtype: int64

Далі розглянемо колонку Dt_Customer: Дата реєстрації клієнта у компанії

In [60]:
data['Dt_Customer'].head()

0    04-09-2012
1    08-03-2014
2    21-08-2013
3    10-02-2014
4    19-01-2014
Name: Dt_Customer, dtype: object

Щоб коректно обробити колонку з датою Dt_Customer, доречно розрахувати кількість днів, протягом яких клієнт є з нами (відносно найновішої дати реєстрації в датасеті). Ця змінна (Customer_Days) матиме значно більшу  цінність, ніж окремі значення року чи місяця.

In [61]:
data['Dt_Customer'] = pd.to_datetime(data['Dt_Customer'], format='%d-%m-%Y')

max_date = data['Dt_Customer'].max()
data['Customer_Days'] = (max_date - data['Dt_Customer']).dt.days

In [63]:
data['Customer_Days'].head()

0    663
1    113
2    312
3    139
4    161
Name: Customer_Days, dtype: int64

In [64]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2216 entries, 0 to 2239
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Year_Birth           2216 non-null   int64
 1   Education            2216 non-null   float64
 2   Marital_Status       2216 non-null   object
 3   Income               2216 non-null   float64
 4   Kidhome              2216 non-null   int64
 5   Teenhome             2216 non-null   int64
 6   Dt_Customer          2216 non-null   datetime64[ns]
 7   Recency              2216 non-null   int64
 8   MntWines             2216 non-null   int64
 9   MntFruits            2216 non-null   int64
 10  MntMeatProducts      2216 non-null   int64
 11  MntFishProducts      2216 non-null   int64
 12  MntSweetProducts     2216 non-null   int64
 13  MntGoldProds         2216 non-null   int64
 14  NumDealsPurchases    2216 non-null   int64
 15  NumWebPurchases      2216 non-null   int64
 16  NumCatalogPurchases  2216 non-null   int64
 17  NumStorePurchases    2216 non-null   int64
 18  NumWebVisitsMonth    2216 non-null   int64
 19  AcceptedCmp3         2216 non-null   int64
 20  AcceptedCmp4         2216 non-null   int64
 21  AcceptedCmp5         2216 non-null   int64
 22  AcceptedCmp1         2216 non-null   int64
 23  AcceptedCmp2         2216 non-null   int64
 24  Complain             2216 non-null   int64
 25  Z_CostContact        2216 non-null   int64
 26  Z_Revenue            2216 non-null   int64
 27  Response             2216 non-null   int64
 28  In_Relationship      2216 non-null   int64
 29  Customer_Days        2216 non-null   int64
dtypes: datetime64[ns](1), float64(2), int64(26), object(1)
memory usage: 536.7+ KB

**Завдання 4**.
1. Запишіть в змінну X ті дані, які будете кластеризувати.
2. Побудуйте кластеризацію з KMeans на 3 кластери.
3. Обчисліть метрику силуету для цієї кластеризації.

In [65]:
X = data.drop(columns = ['Marital_Status', 'Dt_Customer'])

kmeans = KMeans(n_clusters=3)
labels = kmeans.fit_predict(X)

score = silhouette_score(X, labels)
print(f"Silhouette Score: {score:.4f}")

Silhouette Score: 0.6058

**Завдання 5.** Візуалізуйте знайдені кластери разом з наявними даними та проаналізуйте кластери. У нас ознак більше, ніж 2 або 3, тож, тут треба подумати, які саме ознаки варто використати для візуалізації аби вони були інформативними. Рекомендую точно звернути увагу на харакетиристики про дохід користувачів і те, як вони взаємодять з магазинок (кількість покупок і тд).

Для візуалізації зручно може бути використати `plotly.express.scatter_3d` для 3D графіку розсіювання, але тут можна скористатись будь-яким зрозумілим і зручним для вас методом візуалізації. Опишіть свої спостереження, чи кластери мають сенс?

In [70]:
fig = px.scatter_3d(
    X,
    x='Income',
    y='Customer_Days',
    z='NumStorePurchases',
    color=labels,
)
fig.show()

In [71]:
X['Total_Mnt'] = X['MntWines'] + X['MntFruits'] + X['MntMeatProducts'] + X['MntFishProducts'] + X['MntSweetProducts'] + X['MntGoldProds']

fig = px.scatter_3d(
    X,
    x='Income',
    y='Total_Mnt',
    z='Customer_Days',
    color=labels
)
fig.show()

Бачимо що не зовсім доцільно зараз розділяти наші дані на 3 кластери. Алгоритм виділив в окремий кластер лише 1 точку, яка є аномальним викидом із максимально високим доходом (666 666$). Інші два кластери виглядають краще, проте вони є сильно розрідженими та змішаними через відсутність масштабування та великий розмах значень Income.

**Завдання 6**. Масштабуйте дані (StandardScaler/MinMaxScaler) і побудуйте знову кластеризацію KMeans на 3 кластери і обчисліть метрику силуету. Опишіть порівняння з експериментом без масштабування значень.

In [73]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)

In [75]:
X_scaled_df.head()

,Year_Birth,Education,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,...,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,In_Relationship,Customer_Days,Total_Mnt
0,-0.986443,-0.791254,0.234063,-0.823039,-0.928972,0.310532,0.978226,1.549429,1.690227,2.454568,...,-0.280839,-0.261661,-0.117148,-0.097812,0.0,0.0,2.377952,-1.348829,1.529129,1.675488
1,-1.236801,-0.791254,-0.234559,1.039938,0.909066,-0.380509,-0.872024,-0.637328,-0.717986,-0.651038,...,-0.280839,-0.261661,-0.117148,-0.097812,0.0,0.0,-0.420530,-1.348829,-1.188411,-0.962358
2,-0.318822,-0.791254,0.769478,-0.823039,-0.928972,-0.795134,0.358511,0.569159,-0.178368,1.340203,...,-0.280839,-0.261661,-0.117148,-0.097812,0.0,0.0,-0.420530,0.741384,-0.205155,0.280250
3,1.266777,-0.791254,-1.017239,1.039938,-0.928972,-0.795134,-0.872024,-0.561922,-0.655551,-0.504892,...,-0.280839,-0.261661,-0.117148,-0.097812,0.0,0.0,-0.420530,0.741384,-1.059945,-0.919224
4,1.016420,1.589492,0.240221,1.039938,-0.928972,1.554407,-0.391671,0.418348,-0.218505,0.152766,...,-0.280839,-0.261661,-0.117148,-0.097812,0.0,0.0,-0.420530,0.741384,-0.951244,-0.307044

In [74]:
kmeans = KMeans(n_clusters=3, random_state=42)
labels_scaled = kmeans.fit_predict(X_scaled_df)

score_scaled = silhouette_score(X_scaled_df, labels_scaled)
print(f"Silhouette Score (scaled): {score_scaled:.4f}")

Silhouette Score (scaled): 0.2518

In [78]:
fig = px.scatter_3d(
    X_scaled_df,
    x='Income',
    y='Total_Mnt',
    z='Customer_Days',
    color=labels_scaled
)
fig.show()

Після масштабування даних метрика Silhouette Score значно понизилася Silhouette Score (scaled) = 0.2518 (проти 0.6058 на немасштабованих даних). Це пояснюється тим, що високий попередній бал був штучним викривленням через 1 віддалений аномальний викид.

У масштабованому варіанті все ще не видно чіткої логічної закономірності у виділенні 3-го кластера (жовтого кольору). Він містить занадто мало екземплярів і змішаний з іншими. Це чітко вказує на те, що аномальні викиди в даних заважають моделі побудувати правильні межі між сегментами.

**Завдання 7.** З візуалізацій на попередньому кроці ви могли побачити якісь викиди в даних. Опрацюйте викиди (можна видалити ці рядки або придумати інший спосіб).

**Завдання 8.** Виконайте Elbow method для пошуку оптимальної кількості кластерів та натренуйте KMeans з тою кількістю кластерів, яку Elbow method показав як оптимальну. Обчисліть метрику силуету. Візуалізуйте кластери. З яким набором даних (масштабованим чи ні) тут працювати - ваш вибір, можна зробити експеримент з обома.

**Завдання 9.** Використовуючи методи `scipy` `dendrogram, linkage, fcluster`
1. Побудуйте ієрархічну агломеративну кластеризацію з `single linkage` на даних невідмасштабованих, але з прибраним викидом.
2. Візуалізуйте дендрограму. При візуалізації обовʼязково задайте параметр `truncate_mode='lastp'` - це обріже дендрограму, без цього вона буде завелика, бо у нас тут даних суттєво більше, ніж в лекції.
3. Проаналізуйте дендрограму та побудуйте варіанти плоских кластеризацій з `fcluster` на 2 і 3 кластери. Візуалізуйте результати кожної з цих кластеризацій та зробіть висновок. Чи вважаєте ви якусь з цих кластеризацій вдалою? Що спостерігаєте з цих кластеризацій?
4. Порахуйте мерику силуету для цього методу кластеризації.

**Завдання 10.**
1. Використайте метод кластеризації, який ми не використовували в попередніх завданнях цього ДЗ (може бути ієрархічна кластеризація з іншим способом звʼязності або інші методи sklearn).
2. Порахуйте мер=трику силуету і візуалізуйте результат кластеризації. Зробіть висновок про те, чи могла б ця кластеризація бути корисною?